name: Build

on:
  workflow_dispatch:

env:
  FRAMEWORK: net8.0-android
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android workload
        run: dotnet workload install android

      - name: Install Android platform tools
        run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install platform-tools

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish Android
        run: |
          sed -i "s|<string name=\"displayName\" translatable=\"false\">认证器</string>|<string name=\"displayName\" translatable=\"false\">认证器</string>|g" AuthenticatorPro.Droid/Resources/values/strings.xml

          dotnet publish -f:$FRAMEWORK -c:$CONFIGURATION --no-restore AuthenticatorPro.Droid/AuthenticatorPro.Droid.csproj
          APK=$(find AuthenticatorPro.Droid/bin/$CONFIGURATION/$FRAMEWORK/publish -name '*-Signed.apk')
          mv $APK "me.jmh.authenticatorpro.apk"

      - name: Publish Wear OS
        run: |
          sed -i "s|<string name=\"displayName\" translatable=\"false\">认证器</string>|<string name=\"displayName\" translatable=\"false\">认证器</string>|g" AuthenticatorPro.WearOS/Resources/values/strings.xml

          dotnet publish -f:$FRAMEWORK -c:$CONFIGURATION --no-restore AuthenticatorPro.WearOS/AuthenticatorPro.WearOS.csproj
          APK=$(find AuthenticatorPro.WearOS/bin/$CONFIGURATION/$FRAMEWORK/publish -name '*-Signed.apk')
          mv $APK "me.jmh.authenticatorpro.wearos.apk"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AuthenticatorPro
          path: |
            me.jmh.authenticatorpro*.apk
